# Generated by Django 5.2 on 2025-05-12 16:45

import animais.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=animais.models.capa_upload_path)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Fêmea', 'Fêmea'), ('Macho', 'Macho')])),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=20)),
                ('raca', models.CharField(max_length=30)),
                ('disponivel_para_adocao', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='tipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria do Animal',
                'verbose_name_plural': 'Categorias dos Animais',
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=animais.models.animal_image_upload_path)),
                ('animal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animais.animais')),
            ],
        ),
        migrations.AddField(
            model_name='animais',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animais.tipoanimal'),
        ),
    ]
