# Generated by Django 5.2 on 2025-05-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='cor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
