# Generated by Django 5.2 on 2025-05-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animais',
            name='anos',
        ),
        migrations.RemoveField(
            model_name='animais',
            name='meses',
        ),
        migrations.AddField(
            model_name='animais',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animais',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animais',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
