# Generated by Django 5.2 on 2025-08-16 02:39

import animais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaisadotados',
            name='foto',
            field=models.ImageField(upload_to=animais.models.capa_adotado_upload_path),
        ),
    ]
