# Generated by Django 5.2 on 2025-04-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animais',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
    ]
