# Generated by Django 5.2 on 2025-06-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animaisadotados_nome_adotante'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='idade_anos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animais',
            name='idade_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
