# Generated by Django 5.2 on 2025-05-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animais_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animais',
            name='cor',
        ),
    ]
