# Generated by Django 5.2 on 2025-04-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animais_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_capa/'),
        ),
    ]
