# Generated by Django 5.2 on 2025-08-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animaisadotados_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaisadotados',
            name='telefone_adotante',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
