# Generated by Django 5.2 on 2025-05-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_remove_animais_anos_remove_animais_meses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animais',
            name='data_cadastro',
        ),
    ]
