# Generated by Django 5.2 on 2025-08-16 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_alter_animaisadotados_telefone_adotante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaisadotados',
            name='email_adotante',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='animaisadotados',
            name='endereco_adotante',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='animaisadotados',
            name='telefone_adotante',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (99) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')]),
        ),
    ]
