# Generated by Django 5.2 on 2025-04-15 15:38

import animais.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_alter_animais_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=animais.models.animal_image_upload_path)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animais.animais')),
            ],
        ),
    ]
