# Generated by Django 5.2 on 2025-05-16 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_remove_animais_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='idade_anos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anos'),
        ),
        migrations.AddField(
            model_name='animais',
            name='idade_meses',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Meses'),
        ),
    ]
