# Generated by Django 5.2 on 2025-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_animais_idade_anos_animais_idade_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaisadotados',
            name='animal_original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
