# Generated by Django 5.2 on 2025-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_animalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto_capa/'),
        ),
    ]
