# Generated by Django 5.2 on 2025-05-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_remove_animais_idade_anos_remove_animais_idade_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='idade_anos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animais',
            name='idade_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
