# Generated by Django 5.2 on 2025-04-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_alter_animais_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalimage',
            old_name='contact',
            new_name='animal',
        ),
    ]
