# Generated by Django 5.2 on 2025-04-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_rename_contact_animalimage_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalimage',
            old_name='animal',
            new_name='animal_fk',
        ),
    ]
