# Generated by Django 5.2 on 2025-05-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_animais_idade_anos_animais_idade_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animais',
            name='idade_anos',
        ),
        migrations.RemoveField(
            model_name='animais',
            name='idade_meses',
        ),
    ]
