# Generated by Django 5.2 on 2025-05-27 18:16

import animais.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0007_remove_animais_idade_anos_remove_animais_idade_meses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimaisAdotados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=animais.models.adopted_capa_upload_path)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Fêmea', 'Fêmea'), ('Macho', 'Macho')])),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=20)),
                ('raca', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('adotado_em', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animais.tipoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Adotado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('data_adocao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='animais.animaisadotados')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImageAdotado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=animais.models.adopted_gallery_upload_path)),
                ('animal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_adotado', to='animais.animaisadotados')),
            ],
        ),
    ]
