# Generated by Django 5.2 on 2025-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0008_tipoanimal_alter_animais_foto_animais_tipo_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoanimal',
            options={'verbose_name': 'Tipo de Animal', 'verbose_name_plural': 'Tipos de Animais'},
        ),
        migrations.AlterField(
            model_name='animais',
            name='nome',
            field=models.CharField(help_text='Digite o seu nome', max_length=100),
        ),
    ]
