# Generated by Django 5.2 on 2025-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0008_animaisadotados_adotado_animalimageadotado'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='idade_anos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animais',
            name='idade_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
