# Generated by Django 5.2 on 2025-05-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0009_animais_idade_anos_animais_idade_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaisadotados',
            name='descricao',
        ),
    ]
