# Generated by Django 5.2 on 2025-05-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0010_remove_animaisadotados_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
            ],
        ),
        migrations.AlterModelOptions(
            name='animais',
            options={},
        ),
        migrations.AlterField(
            model_name='animais',
            name='porte',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')]),
        ),
        migrations.AlterField(
            model_name='animaisadotados',
            name='porte',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')]),
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='animais.animaisadotados')),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='animais.adoptante')),
            ],
        ),
        migrations.DeleteModel(
            name='Adotado',
        ),
    ]
