# Generated by Django 5.2 on 2025-05-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_admin', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel_superuser',
            field=models.PositiveIntegerField(default=1, verbose_name='Nível do superusuário'),
        ),
    ]
