# Generated by Django 5.2 on 2025-05-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_admin', '0004_profile_nivel_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nivel_superuser',
        ),
    ]
